### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by maciekish** [mapbox/fontmachine#4]
How do we actually use this to turn a TTF into PBF's for MapBox?

**Comment by maciekish** [comment]
cc @zakay @matsbov

**Comment by pksorensen** [comment]
I would like to know the same :)

**Comment by lbud** [comment]
Hey @maciekish @s093294, check out the [Usage](https://github.com/mapbox/fontmachine#usage) section of the README. For a simple example, check out [this test](https://github.com/mapbox/fontmachine/blob/master/test/test.js#L10). `fontmachine.makeGlyphs` returns an object that includes `stack: [Array of PBFs]`

If you have specific questions/suggestions for further clarity feel free to open specific issues.

**Comment by maciekish** [comment]
Thanks for replying @lbud however I think both me and @s093294 have approximately zero node experience.

1) I'm unable to install fontmachine on my new Mac. I installed node and pkg-config via Homebrew, then I'm unable to get past the build error below. The log refers to node 5.0.0 but i have tried 4.1.2 as well. I also tried cloning the git version and installing that with the exact same result. I have the xcode command line tools installed.

2) What do we do with the `stack: [Array of PBFs]` once we have actually installed fontmachine? As i said, zero node experience, coming from iOS just wanting a quick ttf -> pbf conversion :)

```
 % npm install fontmachine                                                                                                                                            ~/Temp Maciejs-MacBook-Air

> fontnik@0.3.2 install /Users/maciekish/Temp/node_modules/fontnik
> node-pre-gyp install --fallback-to-build

  ACTION binding_gyp_action_before_build_target_run_protoc_glyphs Release/obj/gen/glyphs.pb.cc
  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/fontnik/src/node_fontnik.o
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:6:
In file included from /Users/maciekish/.node-gyp/5.0.0/include/node/node.h:42:
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4450:42: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      GenericNamedPropertyGetterCallback getter = 0,
                                         ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4465:38: note: previous declaration is here
  GenericNamedPropertyGetterCallback getter;
                                     ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4451:42: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      GenericNamedPropertySetterCallback setter = 0,
                                         ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4466:38: note: previous declaration is here
  GenericNamedPropertySetterCallback setter;
                                     ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4452:41: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      GenericNamedPropertyQueryCallback query = 0,
                                        ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4467:37: note: previous declaration is here
  GenericNamedPropertyQueryCallback query;
                                    ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4453:43: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      GenericNamedPropertyDeleterCallback deleter = 0,
                                          ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4468:39: note: previous declaration is here
  GenericNamedPropertyDeleterCallback deleter;
                                      ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4454:46: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      GenericNamedPropertyEnumeratorCallback enumerator = 0,
                                             ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4469:42: note: previous declaration is here
  GenericNamedPropertyEnumeratorCallback enumerator;
                                         ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4455:20: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      Local<Value> data = Local<Value>(),
                   ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4470:16: note: previous declaration is here
  Local<Value> data;
               ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4456:28: warning: declaration shadows a field of 'v8::NamedPropertyHandlerConfiguration' [-Wshadow]
      PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                           ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4471:24: note: previous declaration is here
  PropertyHandlerFlags flags;
                       ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4478:37: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      IndexedPropertyGetterCallback getter = 0,
                                    ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4493:33: note: previous declaration is here
  IndexedPropertyGetterCallback getter;
                                ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4479:37: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      IndexedPropertySetterCallback setter = 0,
                                    ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4494:33: note: previous declaration is here
  IndexedPropertySetterCallback setter;
                                ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4480:36: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      IndexedPropertyQueryCallback query = 0,
                                   ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4495:32: note: previous declaration is here
  IndexedPropertyQueryCallback query;
                               ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4481:38: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      IndexedPropertyDeleterCallback deleter = 0,
                                     ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4496:34: note: previous declaration is here
  IndexedPropertyDeleterCallback deleter;
                                 ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4482:41: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      IndexedPropertyEnumeratorCallback enumerator = 0,
                                        ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4497:37: note: previous declaration is here
  IndexedPropertyEnumeratorCallback enumerator;
                                    ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4483:20: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      Local<Value> data = Local<Value>(),
                   ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4498:16: note: previous declaration is here
  Local<Value> data;
               ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4484:28: warning: declaration shadows a field of 'v8::IndexedPropertyHandlerConfiguration' [-Wshadow]
      PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                           ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:4499:24: note: previous declaration is here
  PropertyHandlerFlags flags;
                       ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:7:
../../nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../../nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../../nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../../nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../../nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd
      argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/maciekish/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/maciekish/.node-gyp/5.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/maciekish/.node-gyp/5.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:7:
../../nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:7:
../../nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:6:
In file included from /Users/maciekish/.node-gyp/5.0.0/include/node/node.h:42:
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:6:
In file included from /Users/maciekish/.node-gyp/5.0.0/include/node/node.h:42:
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:6:
In file included from /Users/maciekish/.node-gyp/5.0.0/include/node/node.h:42:
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node_fontnik.cpp:2:
In file included from ../src/glyphs.hpp:6:
In file included from /Users/maciekish/.node-gyp/5.0.0/include/node/node.h:42:
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/maciekish/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../../nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
14 warnings and 10 errors generated.
make: *** [Release/obj.target/fontnik/src/node_fontnik.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/maciekish/Temp/node_modules/fontnik/lib/fontnik.node" "--module_name=fontnik" "--module_path=/Users/maciekish/Temp/node_modules/fontnik/lib"
gyp ERR! cwd /Users/maciekish/Temp/node_modules/fontnik
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/maciekish/Temp/node_modules/fontnik/lib/fontnik.node --module_name=fontnik --module_path=/Users/maciekish/Temp/node_modules/fontnik/lib' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/maciekish/Temp/node_modules/fontnik/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/Users/maciekish/Temp/node_modules/fontnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/maciekish/Temp/node_modules/fontnik
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/maciekish/Temp/node_modules/fontnik/lib/fontnik.node --module_name=fontnik --module_path=/Users/maciekish/Temp/node_modules/fontnik/lib' (1)
npm WARN install:fontnik@0.3.2 fontnik@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fontnik@0.3.2 Exit status 1
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/maciekish/Temp/package.json'
npm WARN EPACKAGEJSON Temp No description
npm WARN EPACKAGEJSON Temp No repository field.
npm WARN EPACKAGEJSON Temp No README data
npm WARN EPACKAGEJSON Temp No license field.
```

**Comment by animaux** [comment]
> just wanting a quick ttf -> pbf conversion

Me too. I’m puzzled.

**Comment by mikemorris** [comment]
@maciekish We commonly use https://github.com/creationix/nvm to install multiple Node.js versions locally - both v4.x and v5.x are quite new and I don't think we've updated the version of https://github.com/nodejs/nan in [node-fontnik](https://github.com/mapbox/node-fontnik) to add support yet - try using Node.js v0.12.x or v0.10.x for now, and I'll look into adding support for v4.x+ soon.

**Comment by mikemorris** [comment]
@maciekish We're consuming pbf-packed glyphs in [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/glyph_atlas.js) and [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/geometry/glyph_atlas.cpp).

**Comment by mikemorris** [comment]
@maciekish https://github.com/mapbox/fontmachine/commit/8f1ee2e7c492c1d4f69c324acbb8458dc183a4a8 bumps the version of [node-fontnik](https://github.com/mapbox/node-fontnik) here to add Node.js v4.x support (I tested this on Node.js v4.2.2). There isn't a node-fontnik binary published for Node.js v5.x, and there appear to be compilation issues building node-fontnik from inside another project, so hold off on that for now. You may also be interested in https://github.com/mapbox/node-fontnik/blob/master/bin/build-glyphs as an alternative interface for building PBFs from font files.
